# Generated by Django 6.0 on 2025-12-31 16:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeArea",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nome")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Criado em"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Área de Conhecimento",
                "verbose_name_plural": "Áreas de Conhecimento",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TutorialTag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Nome"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Criado em"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Tutorial",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Título")),
                ("description", models.TextField(verbose_name="Descrição")),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Publicado"),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("iniciante", "Iniciante"),
                            ("intermediario", "Intermediário"),
                            ("avancado", "Avançado"),
                        ],
                        default="iniciante",
                        max_length=20,
                        verbose_name="Nível de Dificuldade",
                    ),
                ),
                (
                    "estimated_time",
                    models.IntegerField(
                        help_text="Tempo estimado em minutos",
                        verbose_name="Tempo Estimado (min)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Criado em"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Publicado em"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tutorials",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Autor",
                    ),
                ),
                (
                    "knowledge_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tutorials",
                        to="tutorial.knowledgearea",
                        verbose_name="Área de Conhecimento",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="tutorials",
                        to="tutorial.tutorialtag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tutorial",
                "verbose_name_plural": "Tutoriais",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TutorialStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("order", models.IntegerField(verbose_name="Ordem")),
                ("title", models.CharField(max_length=255, verbose_name="Título")),
                (
                    "content",
                    models.TextField(
                        help_text="Conteúdo do passo (HTML/Markdown)",
                        verbose_name="Conteúdo",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Criado em"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "tutorial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="tutorial.tutorial",
                        verbose_name="Tutorial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Passo do Tutorial",
                "verbose_name_plural": "Passos do Tutorial",
                "ordering": ["order"],
                "unique_together": {("tutorial", "order")},
            },
        ),
        migrations.CreateModel(
            name="TutorialMedia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("image", "Imagem"),
                            ("video_upload", "Vídeo (Upload)"),
                            ("video_embed", "Vídeo (Embed)"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Mídia",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="tutorials/%Y/%m/%d/",
                        verbose_name="Arquivo",
                    ),
                ),
                (
                    "embed_url",
                    models.URLField(blank=True, null=True, verbose_name="URL de Embed"),
                ),
                (
                    "caption",
                    models.TextField(blank=True, null=True, verbose_name="Legenda"),
                ),
                (
                    "annotations",
                    models.JSONField(
                        blank=True,
                        help_text="Dados de anotações do Fabric.js/Konva.js em formato JSON",
                        null=True,
                        verbose_name="Anotações",
                    ),
                ),
                ("order", models.IntegerField(verbose_name="Ordem")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Criado em"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="tutorial.tutorialstep",
                        verbose_name="Passo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mídia do Tutorial",
                "verbose_name_plural": "Mídias do Tutorial",
                "ordering": ["order"],
            },
        ),
    ]
