# Generated by Django 5.2.7 on 2026-01-05 00:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sectors", "0002_sector_is_active"),
        ("tags", "0003_tag_is_active"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tutorial",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Título")),
                ("description", models.TextField(verbose_name="Descrição")),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Criado em"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_tutorials",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tutorials",
                        to="sectors.sector",
                        verbose_name="Setor",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="tutorials",
                        to="tags.tag",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_tutorials",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tutorial",
                "verbose_name_plural": "Tutoriais",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TutorialStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("order", models.IntegerField(verbose_name="Ordem")),
                ("title", models.CharField(max_length=255, verbose_name="Título")),
                (
                    "content",
                    models.TextField(
                        help_text="Conteúdo do passo (HTML/Markdown)",
                        verbose_name="Conteúdo",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Criado em"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "tutorial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="tutorial.tutorial",
                        verbose_name="Tutorial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Passo do Tutorial",
                "verbose_name_plural": "Passos do Tutorial",
                "ordering": ["order"],
                "unique_together": {("tutorial", "order")},
            },
        ),
        migrations.CreateModel(
            name="TutorialMedia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("image", "Imagem"),
                            ("video_upload", "Vídeo (Upload)"),
                            ("video_embed", "Vídeo (Embed)"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Mídia",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="tutorials/%Y/%m/%d/",
                        verbose_name="Arquivo",
                    ),
                ),
                (
                    "embed_url",
                    models.URLField(blank=True, null=True, verbose_name="URL de Embed"),
                ),
                (
                    "caption",
                    models.TextField(blank=True, null=True, verbose_name="Legenda"),
                ),
                (
                    "annotations",
                    models.JSONField(
                        blank=True,
                        help_text="Dados de anotações do Fabric.js/Konva.js em formato JSON",
                        null=True,
                        verbose_name="Anotações",
                    ),
                ),
                ("order", models.IntegerField(verbose_name="Ordem")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Criado em"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="tutorial.tutorialstep",
                        verbose_name="Passo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mídia do Tutorial",
                "verbose_name_plural": "Mídias do Tutorial",
                "ordering": ["order"],
            },
        ),
    ]
