# Generated by Django 5.2.7 on 2026-04-25 21:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutorial", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorial",
            name="shared_admins",
            field=models.ManyToManyField(
                blank=True,
                related_name="admin_tutorials",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Administradores Delegados",
            ),
        ),
    ]
