# Generated by Django 5.2.7 on 2026-01-01 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="color",
            field=models.CharField(
                default="#3B82F6", help_text="Hex color code", max_length=7
            ),
        ),
    ]
