# Generated by Django 5.2.7 on 2026-01-01 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0002_tag_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Status da tag (Ativo/Inativo)"
            ),
        ),
    ]
