# Generated by Django 5.2.7 on 2026-01-01 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sectors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sector",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Status do setor (Ativo/Inativo)"
            ),
        ),
    ]
