# Generated by Django 5.2.7 on 2026-01-01 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sectors", "0002_sector_is_active"),
        ("tags", "0003_tag_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="Manual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nome do Manual"),
                ),
                (
                    "pdf_file",
                    models.FileField(upload_to="manuais/", verbose_name="Arquivo PDF"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Status do manual (Ativo/Inativo)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Criado por"
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Atualizado por",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="manuals",
                        to="sectors.sector",
                        verbose_name="Setor",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="manuals",
                        to="tags.tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "verbose_name": "Manual",
                "verbose_name_plural": "Manuais",
                "ordering": ["-created_at"],
            },
        ),
    ]
