# Generated by Django 5.2.7 on 2026-01-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manual", "0001_initial"),
        ("sectors", "0002_sector_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="manual",
            name="sector",
        ),
        migrations.AddField(
            model_name="manual",
            name="sectors",
            field=models.ManyToManyField(
                related_name="manuals", to="sectors.sector", verbose_name="Setores"
            ),
        ),
    ]
