# Generated by Django 5.2.7 on 2026-04-25 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manual", "0002_remove_manual_sector_manual_sectors"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="manual",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_manuals",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Proprietário",
            ),
        ),
        migrations.AddField(
            model_name="manual",
            name="shared_admins",
            field=models.ManyToManyField(
                blank=True,
                related_name="admin_manuals",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Administradores Delegados",
            ),
        ),
        migrations.AlterField(
            model_name="manual",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
        ),
        migrations.AlterField(
            model_name="manual",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Ativo"),
        ),
        migrations.AlterField(
            model_name="manual",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
        ),
    ]
