# Generated by Django 5.2.7 on 2026-01-04 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="exam_duration_minutes",
            field=models.IntegerField(
                default=60,
                help_text="Tempo em minutos que o aluno terá para realizar a prova",
                verbose_name="Duração da Prova (minutos)",
            ),
        ),
    ]
