# Generated by Django 5.2.7 on 2026-04-25 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_question_options_refactor"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_courses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Proprietário",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="shared_admins",
            field=models.ManyToManyField(
                blank=True,
                related_name="admin_courses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Administradores Delegados",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="correct_option",
            field=models.IntegerField(
                default=0, verbose_name="Índice da Alternativa Correta"
            ),
        ),
    ]
